apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev-kube.yml convert -o export
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: ad
  name: ad
spec:
  ports:
  - name: "5009"
    port: 5009
    targetPort: 5000
  selector:
    io.kompose.service: ad
status:
  loadBalancer: {}
