apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev-kube.yml convert -o export
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: badwords-db
  name: badwords-db
spec:
  ports:
  - name: "5441"
    port: 5441
    targetPort: 5432
  selector:
    io.kompose.service: badwords-db
status:
  loadBalancer: {}
