apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev-kube.yml convert -o export
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: messages-db
  name: messages-db
spec:
  type: NodePort
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
    nodePort: 30015
  selector:
    io.kompose.service: messages-db
status:
  loadBalancer: {}


