apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev-kube.yml convert -o export
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: message
  name: message
spec:
  ports:
  - name: "5013"
    port: 5013
    targetPort: 5000
  selector:
    io.kompose.service: message
status:
  loadBalancer: {}
