apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev-kube.yml convert -o export
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: newsfeed
  name: newsfeed
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: newsfeed
    spec:
      containers:
      - env:
        - name: APP_SETTINGS
          value: project.config.DevelopmentConfig
        - name: FLASK_ENV
          value: development
        image: zhongxilu/newsfeed:latest
        name: newsfeed
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
