apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev-kube.yml convert -o export
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: post
  name: post
spec:
  type: NodePort
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5000
  selector:
    io.kompose.service: post
status:
  loadBalancer: {}

