version: '3.3'

networks:
  mynetwork:
    driver: bridge

services:

  frontend:
    image: ${DOCKER_USERNAME}/frontend:latest
    build:
      context: ./services/frontend
      dockerfile: Dockerfile-dev
    ports:
      - 4200:4200
    networks:
      - mynetwork

  users:
    image: ${DOCKER_USERNAME}/users:latest
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    networks:
      - mynetwork

  users-db:
    image: ${DOCKER_USERNAME}/users-db:latest
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  authentication:
    image: ${DOCKER_USERNAME}/authentication:latest
    build:
      context: ./services/authentication
      dockerfile: Dockerfile-dev
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    networks:
      - mynetwork

  authentication-db:
    image: ${DOCKER_USERNAME}/authentication-db:latest
    build:
      context: ./services/authentication/project/db
      dockerfile: Dockerfile
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  post:
    image: ${DOCKER_USERNAME}/post:latest
    build:
      context: ./services/post
      dockerfile: Dockerfile-dev
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@posts-db:5432/posts_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@posts-db:5432/posts_test
    depends_on:
      - posts-db
    networks:
      - mynetwork

  posts-db:
    image: ${DOCKER_USERNAME}/posts-db:latest
    build:
      context: ./services/post/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  newsfeed:
    image: ${DOCKER_USERNAME}/newsfeed:latest
    build:
      context: ./services/newsfeed
      dockerfile: Dockerfile-dev
    ports:
      - 5007:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    networks:
      - mynetwork

  tag:
    image: ${DOCKER_USERNAME}/tag:latest
    build:
      context: ./services/tag
      dockerfile: Dockerfile-dev
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@tags-db:5432/tags_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@tags-db:5432/tags_test
    depends_on:
      - tags-db
    networks:
      - mynetwork

  tags-db:
    image: ${DOCKER_USERNAME}/tags-db:latest
    build:
      context: ./services/tag/project/db
      dockerfile: Dockerfile
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  like:
    image: ${DOCKER_USERNAME}/like:latest
    build:
      context: ./services/like
      dockerfile: Dockerfile-dev
    ports:
      - 5005:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@likes-db:5432/likes_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@likes-db:5432/likes_test
    depends_on:
      - likes-db
    networks:
      - mynetwork

  likes-db:
    image: ${DOCKER_USERNAME}/likes-db:latest
    build:
      context: ./services/like/project/db
      dockerfile: Dockerfile
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  comment:
    image: ${DOCKER_USERNAME}/comment:latest
    build:
      context: ./services/comment
      dockerfile: Dockerfile-dev
    ports:
      - 5006:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@comments-db:5432/comments_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@comments-db:5432/comments_test
    depends_on:
      - comments-db
    networks:
      - mynetwork

  comments-db:
    image: ${DOCKER_USERNAME}/comments-db:latest
    build:
      context: ./services/comment/project/db
      dockerfile: Dockerfile
    ports:
      - 5440:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  anti-cyberbullying:
    image: ${DOCKER_USERNAME}/anti-cyberbullying:latest
    build:
      context: ./services/anti-cyberbullying
      dockerfile: Dockerfile-dev
    ports:
      - 5008:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@badwords-db:5432/badwords_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@badwords-db:5432/badwords_test
    depends_on:
      - badwords-db
    networks:
      - mynetwork

  badwords-db:
    image: ${DOCKER_USERNAME}/badwords-db:latest
    build:
      context: ./services/anti-cyberbullying/project/db
      dockerfile: Dockerfile
    ports:
      - 5441:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  ad:
    image: ${DOCKER_USERNAME}/ad:latest
    build:
      context: ./services/ad
      dockerfile: Dockerfile-dev
    ports:
      - 5009:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@ads-db:5432/ads_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@ads-db:5432/ads_test
    depends_on:
      - ads-db
    networks:
      - mynetwork

  ads-db:
    image: ${DOCKER_USERNAME}/ads-db:latest
    build:
      context: ./services/ad/project/db
      dockerfile: Dockerfile
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  notification:
    image: ${DOCKER_USERNAME}/notification:latest
    build:
      context: ./services/notification
      dockerfile: Dockerfile-dev
    ports:
      - 5010:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@notifications-db:5432/notifications_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@notifications-db:5432/notifications_test
    depends_on:
      - notifications-db
    networks:
      - mynetwork

  notifications-db:
    image: ${DOCKER_USERNAME}/notifications-db:latest
    build:
      context: ./services/notification/project/db
      dockerfile: Dockerfile
    ports:
      - 5443:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  follow:
    image: ${DOCKER_USERNAME}/follow:latest
    build:
      context: ./services/follow
      dockerfile: Dockerfile-dev
    ports:
      - 5011:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@notifications-db:5432/notifications_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@notifications-db:5432/notifications_test
    networks:
      - mynetwork

  follow-db:
    image: ${DOCKER_USERNAME}/follow-db:latest
    build:
      context: ./services/follow/project/db
      dockerfile: Dockerfile
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  friend:
    image: ${DOCKER_USERNAME}/friend:latest
    build:
      context: ./services/friend
      dockerfile: Dockerfile-dev
    ports:
      - 5012:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@notifications-db:5432/notifications_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@notifications-db:5432/notifications_test
    networks:
      - mynetwork

  friends-db:
    image: ${DOCKER_USERNAME}/friends-db:latest
    build:
      context: ./services/friend/project/db
      dockerfile: Dockerfile
    ports:
      - 5445:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  message:
    image: ${DOCKER_USERNAME}/message:latest
    build:
      context: ./services/message
      dockerfile: Dockerfile-dev
    ports:
      - 5013:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@notifications-db:5432/notifications_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@notifications-db:5432/notifications_test
    networks:
      - mynetwork

  messages-db:
    image: ${DOCKER_USERNAME}/messages-db:latest
    build:
      context: ./services/message/project/db
      dockerfile: Dockerfile
    ports:
      - 5446:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  poll:
    image: ${DOCKER_USERNAME}/poll:latest
    build:
      context: ./services/poll
      dockerfile: Dockerfile-dev
    ports:
      - 5014:5000
    networks:
      - mynetwork
